site_name: Game Guard Documentation
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
    # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: "material"
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation-tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
    - theme.palette
    - content.action.edit
  language: en
  palette:
    primary: deep orange
    accent: deep orange
    scheme: slate
plugins:
  - search
  - git-revision-date-localized
  # - git-committers:
  #     repository: Game-Guard/Documentation-V2
  #     branch: main
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com
    - icon: fontawesome/brands/github
      link: https://github.com
edit_uri: https://github.com/Game-Guard/Documentation-V2/edit/main/docs/
copyright: Copyright &copy; 2023 - 2024 Game Guard
